# Config version. Do not change this
config-version = "1.0"
# What port should the proxy be bound to? By default, we'll bind to all addresses on port 25577.
bind = "0.0.0.0:25577"
# What should be the MOTD? This gets displayed when the player adds your server to
# their server list. Legacy color codes and JSON are accepted.
motd = "&#09add3A dedsafio velocity"
# What should we display for the maximum number of players? (Velocity does not support a cap
# on the number of players online.)
show-max-players = 200
# Should we authenticate players with Mojang? By default, this is on.
online-mode = true
# Should we forward IP addresses and other data to backend servers?
# Available options:
# - "none":        No forwarding will be done. All players will appear to be connecting
#                  from the proxy and will have offline-mode UUIDs.
# - "legacy":      Forward player IPs and UUIDs in a BungeeCord-compatible format. Use this
#                  if you run servers using Minecraft 1.12 or lower.
# - "bungeeguard": Forward player IPs and UUIDs in a format supported by the BungeeGuard
#                  plugin. Use this if you run servers using Minecraft 1.12 or lower, and are
#                  unable to implement network level firewalling (on a shared host).
# - "modern":      Forward player IPs and UUIDs as part of the login process using
#                  Velocity's native forwarding. Only applicable for Minecraft 1.13 or higher.
player-info-forwarding-mode = "modern"
# If you are using modern or BungeeGuard IP forwarding, configure a unique secret here. DONT USE THIS SECRET
forwarding-secret = "ZJnI3bEYn1D6"

[servers]
        # Configure your servers here. Each key represents the server's name, and the value
        # represents the IP address of the server to connect to.
        sv1 = "sv1"
        sv2 = "sv2"
        sv3 = "sv3"
        sv4 = "sv4"
        sv5 = "sv5"
        sv6 = "sv6"
        lobby = "lobby"
        # In what order we should try servers when a player logs in or is kicked from a server.
        try = ["lobby"]

[forced-hosts]
        # Configure your forced hosts here.

[advanced]
        # Enables TCP fast open support on the proxy. Requires the proxy to run on Linux.
        tcp-fast-open = true
        # Enable proxy protocol for load balancers.
        proxy-protocol = false