version: "3"

services:
  skin_tool_python:
    image: jcedeno/skin-tool-python:latest
    ports:
      - "8069:5000"
    restart: unless-stopped
  ipfs_client:
    image: yeasy/ipfs:latest
    ports:
      - "4001:4001"
      - "5002:5002"
      - "8080:8080"
    restart: unless-stopped
    stdin_open: true
    tty: true
  skin_tool_api:
    image: jcedeno/skin-tool-python:latest
    ports:
      - "42069:8080"
    environment:
      MINESKIN_KEY: "PURPUR"
      IPFS_HOST: "/ip4/ipfs_client/tcp/5001"
      SKIN_TOOL_PYTHON_URI: "http://skin_tool_python:8069"
    restart: unless-stopped
    stdin_open: true
    tty: true
