version: "3"

services:
  skin_tool_python:
    image: jcedeno/skin-tool-python:latest
    ports:
      - "8069:5000"
    restart: unless-stopped
  skin_tool_api:
    image: jcedeno/skin-tool-ipfs:latest
    ports:
      - "42069:8080"
    environment:
      MINESKIN_KEY: "PURPUR"
      IPFS_HOST: "/ip4/ipfs_client/tcp/5001"
      SKIN_TOOL_PYTHON_URI: "http://skin_tool_python:8069"
    restart: unless-stopped
    stdin_open: true
    tty: true
